version: '3'
services:
  card-scanner-api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./credentials.json:/app/credentials.json
      # Mount data directory with read-write access
      - ./src/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is shown in logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"