version: '2'

services:
  card-scanner-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      PYTHONPATH: /app
      PYTORCH_DEVICE: cpu
    volumes:
      - ./credentials.json:/app/credentials.json