version: '2'
services:
  card-scanner-api:
    image: python:3.9-slim
    ports:
      - "5000:5000"
    command: bash -c "apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && pip install -r /app/requirements.txt && python /app/simple_card_api.py"
    volumes:
      - ./src/api:/app
      - ./src/tools:/app/tools
      - ./src/api/requirements.txt:/app/requirements.txt
      - ./credentials.json:/app/credentials.json
    working_dir: /app