version: '3'
services:
  card-scanner-api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./credentials.json:/app/credentials.json
      # Mount hash database file directly to avoid directory issues
      - ./src/data/hashes_dphash_16.json:/app/data/hashes_dphash_16.json
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is shown in logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"