version: '3'

services:
  card-scanner-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/tools:/app/tools
      - ./src/data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY}
    env_file:
      - .env
