version: '2.4'

services:
  card-scanner-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY}
      - PYTORCH_DEVICE=cpu
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./model_cache:/root/.cache/torch
    mem_limit: 4g