version: '3'

services:
  card-scanner-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY}
      # Set to CPU by default, change to cuda:0 if you have a GPU
      - PYTORCH_DEVICE=cpu
    volumes:
      # Mount credentials file if you prefer using it instead of environment variable
      - ./credentials.json:/app/credentials.json
      # Mount a cache directory for model weights to avoid re-downloading
      - ./model_cache:/root/.cache/torch
    # Memory limits (compatible with most Docker versions)
    mem_limit: 4g