version: '3'

services:
  card-scanner-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./src/tools:/app/tools
      - ./src/data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
